### ISSUE TITLE
Support scss

### ISSUE THREAD

**Issue by megawac** [vinpac/sublime-simple-import#4]
Relative sass importing would be awesome!

**Comment by vinpac** [comment]
I think it would be awesome too. I will push it later, thank you!

**Comment by vinpac** [comment]
It still pretty basic yet, but I'll add more features further on. Maybe a `import all` would be cool.
Note: It doesn't look for duplicated imports yet, because I've actually focused more on improving the interpreter than making the scss importer for now.

If it doesn't fit your needs, let met know and I'll reopen this issue.

**Comment by megawac** [comment]
Awesome that was fast mate! I'll play around with it thanks!
